tunnel: REPLACE_WITH_YOUR_TUNNEL_UUID
credentials-file: /Users/homelab/.cloudflared/REPLACE_WITH_YOUR_TUNNEL_UUID.json

ingress:
  - hostname: jellyfin.mynkie.com
    service: http://127.0.0.1:80

    # add future sub-domains here

  - service: http_status:404