tunnel: 25cf4712-ce33-4bca-801f-171b01d02bb2
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: jellyfin.mynkie.com
    service: http://nginx:8080
  - hostname: mynkie.com
    service: http://nginx:8080
  - hostname: docs.mynkie.com
    service: http://nginx:8080

  - service: http_status:404
